name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
          scandir: './'
          ignore_paths: '.git'
          ignore_names: ''

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Smoke tests
        run: |
          chmod +x bin/* tests/noreg.sh
          ./bin/relay help
          ./bin/relay version
          ./bin/relay-doctor || true
          # events init uses ~/.local/state; should be fine in CI
          ./bin/relay-events init
          # non-regression script (won't find protected dirs; still passes)
          ./tests/noreg.sh || true
